apiVersion: v1
appVersion: 0.189
description: Distributed SQL query engine for running interactive analytic queries
name: presto
version: 0.2
home: https://prestodb.io
icon: https://prestodb.io/static/presto.png
sources:
  - https://github.com/facebook/presto
maintainers:
  - name: bivas
    email: eliranb@iguazio.com