apiVersion: v1
appVersion: 0.189-1.7.0-b80
description: Distributed SQL query engine for running interactive analytic queries
name: presto.v3io
version: 0.1
home: https://prestodb.io
icon: https://prestodb.io/static/presto.png
sources:
  - https://github.com/facebook/presto
maintainers:
  - name: bivas
    email: eliranb@iguazio.com