presto:
  server:
    log:
      com.facebook.presto: INFO
      io.iguaz.v3io: DEBUG
      io.iguaz.v3io.daemon: INFO
  config:
    mapPath: /etc/config/presto

  image:
    repository: iguaziodocker/presto
    tag: 0.189-1.5.2
    command: /etc/config/v3io/v3io-presto.sh

  environment:
    template: v3io-configs.deployment.env

  volumes:
    coordinator:
      volumesTemplate: v3io-configs.deployment.mount
      volumeMountsTemplate: v3io-configs.deployment.volumeMounts
    worker:
      volumesTemplate: v3io-configs.deployment.mount
      volumeMountsTemplate: v3io-configs.deployment.volumeMounts

nameOverride: presto

global:
  v3io:
    configPath: /etc/config/v3io

v3io:
  username: iguazio
  tenant: iguazio
  password: iguazio
