name: spark
version: 0.4
appVersion: "2.1.2"
description: Fast and general-purpose cluster computing system.
home: http://spark.apache.org
icon: http://spark.apache.org/images/spark-logo-trademark.png
sources:
  - https://github.com/kubernetes/kubernetes/tree/master/examples/spark
  - https://github.com/apache/spark
maintainers:
  - name: Lachlan Evenson
    email: lachlan.evenson@gmail.com
  - name: bivas
    email: eliranb@iguazio.com
